FROM ubuntu

MAINTAINER Guoweikuang guowekuang2015@gmail.com

ADD sources.list /etc/apt/sources.list 
RUN apt-get update -y && apt-get install -y python-pip python-dev build-essential curl net-tools vim nginx vim


RUN mkdir -p /home/guoweikuang 
COPY socket_server.py /home/guoweikuang/socket_server.py 
COPY socket_addr.py /home/guoweikuang/socket_addr.py

WORKDIR /home/guoweikuang 

EXPOSE 5000

CMD ["python", "socket_server.py"] 